# KinoLenta action

name: KinoLentaBuild

on:
  pull_request:
    paths-ignore:
      - '*.md'      
    branches: 
      - master

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Xcode select
      - run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
      - name: Xcode version
      - run: /usr/bin/xcodebuild -version
      - name: Proj build
      - run: xcodebuild -sdk iphoneos -allowProvisioningUpdates -project Kinolenta.xcodeproj
    
